###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
    mailhog:
      image: mailhog/mailhog:latest
      container_name: phpdocker-io-mailhog
      ports:
        - "10001:8025"

    mysql:
      image: mysql:5.7
      container_name: phpdocker-io-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root-password
        - MYSQL_DATABASE=phpdockerio
        - MYSQL_USER=username
        - MYSQL_PASSWORD=password
      ports:
        - "10002:3306"

    webserver:
      image: nginx:alpine
      container_name: phpdocker-io-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "10000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: phpdocker-io-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

    frontend-builder:
      image: node:9-alpine
      container_name: phpdocker-io-frontend-builder
      working_dir: /application
      volumes:
          - .:/application
      command: ['bin/frontend-builder.sh']
