###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  memcached:
    image: phpdockerio/memcached:latest
    container_name: phpdocker-io-memcached

  mailhog:
    image: phpdockerio/mailhog:latest
    container_name: phpdocker-io-mailhog
    ports:
      - "10001:8025"

  mysql:
    image: mysql:5.7
    container_name: phpdocker-io-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=phpdockerio
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password

  webserver:
    image: phpdockerio/nginx:latest
    container_name: phpdocker-io-webserver
    volumes:
        - .:/var/www/phpdocker-io
        - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "10000:80"
    links:
     - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: phpdocker/php-fpm/Dockerfile
    container_name: phpdocker-io-php-fpm
    volumes:
      - .:/var/www/phpdocker-io
      - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
    links:
      - memcached
      - mailhog
      - mysql
