###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

phpdocker-io-memcached:
  image: tenstartups/memcached:latest
  container_name: phpdocker-io-memcached

phpdocker-io-mailhog:
  image: diyan/mailhog
  container_name: phpdocker-io-mailhog
  ports:
    - "10001:8025"

phpdocker-io-mysql:
  image: mysql:5.7
  container_name: phpdocker-io-mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root-password
    - MYSQL_DATABASE=phpdockerio
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password

phpdocker-io-webserver:
  build: .
  dockerfile: docker/Dockerfile.nginx.conf
  container_name: phpdocker-io-webserver
  volumes:
      - ..:/var/www/phpdocker-io
  ports:
   - "10000:80"
  links:
   - phpdocker-io-php-fpm

phpdocker-io-php-fpm:
  build: .
  dockerfile: docker/Dockerfile.php-fpm.conf
  container_name: phpdocker-io-php-fpm
  volumes:
    - ..:/var/www/phpdocker-io
  links:
    - phpdocker-io-memcached
    - phpdocker-io-mailhog
    - phpdocker-io-mysql
