#easy_admin_bundle:
#    resource: "@App/Controller/AdminController.php"
#    type:     annotation
#    prefix:   /site-admin

home:
    path:     /
    defaults: { _controller: App\Controller\PagesController::homeAction }
    methods:  [GET]

post:
    path:     /post/{slug}
    defaults: { _controller: App\Controller\PostController::showPostAction }
    methods:  [GET, POST]

contact:
    path:     /contact
    defaults: { _controller: App\Controller\PagesController::contactRequestAction }
    methods:  [GET, POST]

generator:
    path:     /generator
    defaults: { _controller: App\Controller\GeneratorController::createAction }
    methods:  [GET, POST]
