home:
    path:      /
    defaults:  { _controller: AppBundle:Pages:home }
    methods: [GET]

generator:
    path:      /generator
    defaults:  { _controller: AppBundle:Builder:create }
    methods: [GET, POST]
