home:
    path:      /
    defaults:  { _controller: AppBundle:Pages:home }
    methods: [GET]

post:
    path:     /post/{slug}
    defaults:  { _controller: AppBundle:Post:showPost }
    methods: [GET]

contact:
    path:      /contact
    defaults:  { _controller: AppBundle:Pages:contactRequest }
    methods: [GET, POST]

generator:
    path:      /generator
    defaults:  { _controller: AppBundle:Builder:create }
    methods: [GET, POST]
