home:
    path:      /
    defaults:  { _controller: AppBundle:Builder:create }
    methods: [GET]

create_build_environment:
    path:      /
    defaults:  { _controller: AppBundle:Builder:create }
    methods: [GET, POST]
