parameters:
  recaptcha_verify_token_endpoint: https://www.google.com/recaptcha/api/siteverify

services:
  docker_generator:
      class:    AuronConsultingOSS\Docker\Generator\Generator
      factory: [AuronConsultingOSS\Docker\Generator\Factory, create]

  guzzle:
      class: GuzzleHttp\Client

  recaptcha_validator:
      class:     AppBundle\Services\RecaptchaValidator
      arguments: [%recaptcha_secret_key%, %recaptcha_verify_token_endpoint%]
      calls:
        - [setContainer, ["@service_container"]]
